### ISSUE TITLE
[Suggestion] Specify preferred queue ordering with flag or config

### ISSUE THREAD

**Issue by j6k4m8** [jhuapl-boss/ingest-client#21]
There are certainly cases where an arbitrary upload order is preferable — but it would be very helpful to be able to specify `upload_order=contiguous` on some workers to ensure that a new plugin is working correctly, without having to wait for ≈*dataset_size-(dataset_size/cuboid_size)* uploads to finish first.

Possible similar functionality is setting a smaller ingest extent and conducting a smaller test-ingest first, but this would make it easier to get results into the hands of users quicker, without configuring multiple ingest jobs.

**Comment by movestill** [comment]
I think this change would mainly be how we populate the tile upload queue. Someone is actually looking at optimizing the lambda that's responsible for this. Not sure we have the bandwidth to take it further to provide an option to order things by cuboid, also. Could be a good task for an intern!
