### ISSUE TITLE
Engine should take a config object

### ISSUE THREAD

**Issue by straz** [jhuapl-boss/ingest-client#4]
The constructor for `ingest.core.engine.Engine` should take a `configuration` object, so `Engine`s can be created programmatically. The `configuration` object can be a `dict` representing the contents of a configuration file.

For convenience, and to preserve the current behavior, it should be ok to pass a filename, which gets parsed into a configuration object.

**Comment by dkleissa** [comment]
PR accepted with minor edits and will be in next release. We should probably revisit this in the future as manually creating an ArgumentParser instance is outside the `main()` method is a bit odd, but work for now.
